language: node_js
node_js:
 - "stable"
install: yarn
script: yarn test
cache:
  directories:
    - "node_modules"
    - "test"
# safelist
branches:
  only:
  - development
before_script:
  psql -U postgres -c 'create database teamwork-dev;' &&
  psql -U postgres -d travis_ci_test -a -f setupdb.sql
services:
  -postgresql
after_success: yarn coverage