language: node_js
node_js:
 - "stable"
install: yarn
script: yarn test
cache:
  directories:
    - "node_modules"
    - "test"
# safelist
branches:
  only:
  - development
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres &&
  - psql -U postgres -d travis_ci_test -a -f setupdb.sql
after_success: yarn coverage