language: node_js
node_js:
 - "stable"
install: yarn
script: yarn test
cache:
  directories:
    - "node_modules"
    - "test"
# safelist
branches:
  only:
  - development
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE teamwork_dev;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
after_success: yarn coverage